config/routes.rb
R4music::Application.routes.draw do
  resources :composers

  resources :editions

  resources :works

end

app/models/composer.rb
class Composer < ActiveRecord::Base
  has_many :works
end

app/models/edition.rb
class Edition < ActiveRecord::Base
belongs_to :work
end

app/models/work.rb
class Work < ActiveRecord::Base
  belongs_to :composer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/composers_controller.rb
class ComposersController < ApplicationController
  # GET /composers
  # GET /composers.json
  def index
    @composers = Composer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @composers }
    end
  end

  # GET /composers/1
  # GET /composers/1.json
  def show
    @composer = Composer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @composer }
    end
  end

  # GET /composers/new
  # GET /composers/new.json
  def new
    @composer = Composer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @composer }
    end
  end

  # GET /composers/1/edit
  def edit
    @composer = Composer.find(params[:id])
  end

  # POST /composers
  # POST /composers.json
  def create
    @composer = Composer.new(params[:composer])

    respond_to do |format|
      if @composer.save
        format.html { redirect_to @composer, notice: 'Composer was successfully created.' }
        format.json { render json: @composer, status: :created, location: @composer }
      else
        format.html { render action: "new" }
        format.json { render json: @composer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /composers/1
  # PUT /composers/1.json
  def update
    @composer = Composer.find(params[:id])

    respond_to do |format|
      if @composer.update_attributes(params[:composer])
        format.html { redirect_to @composer, notice: 'Composer was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @composer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /composers/1
  # DELETE /composers/1.json
  def destroy
    @composer = Composer.find(params[:id])
    @composer.destroy

    respond_to do |format|
      format.html { redirect_to composers_url }
      format.json { head :ok }
    end
  end
end

app/controllers/editions_controller.rb
class EditionsController < ApplicationController
  # GET /editions
  # GET /editions.json
  def index
    @editions = Edition.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @editions }
    end
  end

  # GET /editions/1
  # GET /editions/1.json
  def show
    @edition = Edition.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @edition }
    end
  end

  # GET /editions/new
  # GET /editions/new.json
  def new
    @edition = Edition.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @edition }
    end
  end

  # GET /editions/1/edit
  def edit
    @edition = Edition.find(params[:id])
  end

  # POST /editions
  # POST /editions.json
  def create
    @edition = Edition.new(params[:edition])

    respond_to do |format|
      if @edition.save
        format.html { redirect_to @edition, notice: 'Edition was successfully created.' }
        format.json { render json: @edition, status: :created, location: @edition }
      else
        format.html { render action: "new" }
        format.json { render json: @edition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /editions/1
  # PUT /editions/1.json
  def update
    @edition = Edition.find(params[:id])

    respond_to do |format|
      if @edition.update_attributes(params[:edition])
        format.html { redirect_to @edition, notice: 'Edition was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @edition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /editions/1
  # DELETE /editions/1.json
  def destroy
    @edition = Edition.find(params[:id])
    @edition.destroy

    respond_to do |format|
      format.html { redirect_to editions_url }
      format.json { head :ok }
    end
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  # GET /works
  # GET /works.json
  def index
    @works = Work.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @works }
    end
  end

  # GET /works/1
  # GET /works/1.json
  def show
    @work = Work.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @work }
    end
  end

  # GET /works/new
  # GET /works/new.json
  def new
    @work = Work.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @work }
    end
  end

  # GET /works/1/edit
  def edit
    @work = Work.find(params[:id])
  end

  # POST /works
  # POST /works.json
  def create
    @work = Work.new(params[:work])

    respond_to do |format|
      if @work.save
        format.html { redirect_to @work, notice: 'Work was successfully created.' }
        format.json { render json: @work, status: :created, location: @work }
      else
        format.html { render action: "new" }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /works/1
  # PUT /works/1.json
  def update
    @work = Work.find(params[:id])

    respond_to do |format|
      if @work.update_attributes(params[:work])
        format.html { redirect_to @work, notice: 'Work was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work = Work.find(params[:id])
    @work.destroy

    respond_to do |format|
      format.html { redirect_to works_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/composers_helper.rb
module ComposersHelper
end

app/helpers/editions_helper.rb
module EditionsHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/composers/_form.html.erb
<%= form_for(@composer) do |f| %>
  <% if @composer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@composer.errors.count, "error") %> prohibited this composer from being saved:</h2>

      <ul>
      <% @composer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/composers/edit.html.erb
<h1>Editing composer</h1>

<%= render 'form' %>

<%= link_to 'Show', @composer %> |
<%= link_to 'Back', composers_path %>

app/views/composers/index.html.erb
<h1>Listing composers</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @composers.each do |composer| %>
  <tr>
    <td><%= composer.first_name %></td>
    <td><%= composer.last_name %></td>
    <td><%= link_to 'Show', composer %></td>
    <td><%= link_to 'Edit', edit_composer_path(composer) %></td>
    <td><%= link_to 'Destroy', composer, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Composer', new_composer_path %>

app/views/composers/new.html.erb
<h1>New composer</h1>

<%= render 'form' %>

<%= link_to 'Back', composers_path %>

app/views/composers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @composer.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @composer.last_name %>
</p>


<%= link_to 'Edit', edit_composer_path(@composer) %> |
<%= link_to 'Back', composers_path %>

app/views/editions/_form.html.erb
<%= form_for(@edition) do |f| %>
  <% if @edition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@edition.errors.count, "error") %> prohibited this edition from being saved:</h2>

      <ul>
      <% @edition.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :work_id %><br />
    <%= f.number_field :work_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :publisher %><br />
    <%= f.text_area :publisher %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/editions/edit.html.erb
<h1>Editing edition</h1>

<%= render 'form' %>

<%= link_to 'Show', @edition %> |
<%= link_to 'Back', editions_path %>

app/views/editions/index.html.erb
<h1>Listing editions</h1>

<table>
  <tr>
    <th>Work</th>
    <th>Description</th>
    <th>Publisher</th>
    <th>Year</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @editions.each do |edition| %>
  <tr>
    <td><%= edition.work_id %></td>
    <td><%= edition.description %></td>
    <td><%= edition.publisher %></td>
    <td><%= edition.year %></td>
    <td><%= edition.price %></td>
    <td><%= link_to 'Show', edition %></td>
    <td><%= link_to 'Edit', edit_edition_path(edition) %></td>
    <td><%= link_to 'Destroy', edition, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Edition', new_edition_path %>

app/views/editions/new.html.erb
<h1>New edition</h1>

<%= render 'form' %>

<%= link_to 'Back', editions_path %>

app/views/editions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Work:</b>
  <%= @edition.work_id %>
</p>

<p>
  <b>Description:</b>
  <%= @edition.description %>
</p>

<p>
  <b>Publisher:</b>
  <%= @edition.publisher %>
</p>

<p>
  <b>Year:</b>
  <%= @edition.year %>
</p>

<p>
  <b>Price:</b>
  <%= @edition.price %>
</p>


<%= link_to 'Edit', edit_edition_path(@edition) %> |
<%= link_to 'Back', editions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>R4music</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/works/_form.html.erb
<%= form_for(@work) do |f| %>
  <% if @work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work.errors.count, "error") %> prohibited this work from being saved:</h2>

      <ul>
      <% @work.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :composer_id %><br />
    <%= f.number_field :composer_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/works/edit.html.erb
<h1>Editing work</h1>

<%= render 'form' %>

<%= link_to 'Show', @work %> |
<%= link_to 'Back', works_path %>

app/views/works/index.html.erb
<h1>Listing works</h1>

<table>
  <tr>
    <th>Composer</th>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @works.each do |work| %>
  <tr>
    <td><%= work.composer_id %></td>
    <td><%= work.title %></td>
    <td><%= link_to 'Show', work %></td>
    <td><%= link_to 'Edit', edit_work_path(work) %></td>
    <td><%= link_to 'Destroy', work, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Work', new_work_path %>

app/views/works/new.html.erb
<h1>New work</h1>

<%= render 'form' %>

<%= link_to 'Back', works_path %>

app/views/works/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Composer:</b>
  <%= @work.composer_id %>
</p>

<p>
  <b>Title:</b>
  <%= @work.title %>
</p>


<%= link_to 'Edit', edit_work_path(@work) %> |
<%= link_to 'Back', works_path %>